<<: !include capuchin-common.yaml

repositories:
  - path: ssh://borg-capuchin@marmoset/var/marmoset/backups/borg/capuchin/repo
    label: marmoset

compression: zstd,6
archive_name_format: capuchin-{now:%Y-%m-%dT%H:%M:%S}

ssh_command: ssh -i /etc/borg-marmoset/ssh_key -o UserKnownHostsFile=/etc/borg-marmoset/known_hosts -o StrictHostKeyChecking=yes -o IdentitiesOnly=yes
encryption_passcommand: cat /etc/borg-marmoset/passphrase

keep_daily: 14
keep_weekly: 8
keep_monthly: 12
keep_yearly: 5
